# Background colors
MAIN_BG = "#37354B"
WHITE = "#FFFFFF"
GREEN = "#77FF00"
GREEN_2 = "#77FF46"
RED = "#FF0033"
RED_2 = "#C30003"
BACKGROUND = "#212237"
INNER_BG = "#616483"
TABLE_BG = "#302746"
PURPLE = "#BA89FF"
BUTTON = "#AF6DFF"
BUTTON_BG = "#5C4895"

# List of currency to show
TICKER_PAIRS = [
    ("BTCUSDT", "BTC/USDT"), ("ETHUSDT", "ETH/USDT"),
    ("XRPUSDT", "XRP/USDT"), ("BNBUSDT", "BNB/USDT"),
    ("SOLUSDT", "SOL/USDT"), ("TRXUSDT", "TRX/USDT"),
    ("DOGEUSDT", "DOGE/USDT"), ("ADAUSDT", "ADA/USDT"),
    ("BCHUSDT", "BCH/USDT")
]
